# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Rpg.Api_HostAddress = http://localhost:5222

GET {{Rpg.Api_HostAddress}}/items

###
POST {{Rpg.Api_HostAddress}}/users/register
Content-Type: application/json

{
  "username": "natsu2597",
  "email": "atulrishi2597@gmail.com",
  "password": "natsuSAMA@12345"
}

###
GET http://localhost:5177/items

###
GET http://localhost:5177/items
