# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Rpg.Api_HostAddress = http://localhost:5222

GET {{Rpg.Api_HostAddress}}/items

###
POST {{Rpg.Api_HostAddress}}/users/register
Content-Type: application/json

{
  "username": "yeshu420",
  "email": "yashrishi2001@gmail.com",
  "password": "password@12345"
}

###
GET http://localhost:5177/items

###
GET http://localhost:5177/items
